general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2

    col.active_border = rgba(fe8019ee) rgba(fabd2fee) 45deg
    col.inactive_border = rgba(3c3836aa)

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 12
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 0.96

    shadow {
        enabled = true
        range = 24
        render_power = 3
        color = rgba(1d2021aa)
    }

    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = false
        vibrancy = 0.17
    }
}

animations {
    enabled = yes, please :)

    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    animation = global,        1, 8,  default
    animation = border,        1, 5,  easeOutQuint
    animation = windows,       1, 4,  easeOutQuint
    animation = windowsIn,     1, 4,  easeOutQuint, popin 87%
    animation = windowsOut,    1, 1.5, linear,      popin 87%
    animation = fadeIn,        1, 1.7, almostLinear
    animation = fadeOut,       1, 1.5, almostLinear
    animation = fade,          1, 3,   quick
    animation = layers,        1, 3.8, easeOutQuint
    animation = layersIn,      1, 4,   easeOutQuint, fade
    animation = layersOut,     1, 1.5, linear,       fade
    animation = fadeLayersIn,  1, 1.8, almostLinear
    animation = fadeLayersOut, 1, 1.4, almostLinear
    animation = workspaces,    1, 2,   almostLinear, fade
    animation = workspacesIn,  1, 1.2, almostLinear, fade
    animation = workspacesOut, 1, 2,   almostLinear, fade
    animation = zoomFactor,    1, 7,   quick
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vfr = true
    vrr = 1
    focus_on_activate = false
    enable_swallow = false
}

cursor {
    inactive_timeout = 5
    no_warps = false
}
