#!/usr/bin/env python


import os
import sys
import pathlib

configs_dir = os.path.expanduser(sys.argv[1])
config_files = os.listdir(configs_dir)
files_full_path = [str(pathlib.Path(configs_dir).joinpath(f)) for f in config_files]
files_full_path = [f for f in files_full_path if os.path.isfile(f)]
kubeconfig_value = ":".join(files_full_path)
print(kubeconfig_value)
