#!/usr/bin/env python
import subprocess
import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]


try:
    branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip().decode() 
except subprocess.CalledProcessError:
    branch = ""


regex = r'(\w+-\d+)'
print(branch)
if re.match(regex, branch):
    issue = re.match(regex, branch).group(1)
    with open(commit_msg_filepath, 'r+') as fh:
        commit_msg = fh.read()
        fh.seek(0, 0)
        fh.write('[%s] %s' % (issue, commit_msg))
elif branch != 'master' and branch != 'dev':
    print('Incorrect branch name')
    sys.exit(1)
elif branch == "":
    print("You are in a detached HEAD state")
    sys.exit(0)
